CREATE DATABASE university;
USE university;
CREATE TABLE student(
student_id INT,
student_name VARCHAR(20),
birth_date DATE,
branch VARCHAR(20),
state VARCHAR(20));

DESCRIBE student;
INSERT INTO student VALUES(194001,'PRANAB','1999-03-17','CSE','PUNJAB');
INSERT INTO student VALUES(194002,'PRAKASH','2000-08-07','ECE','TAMIL NADU');
INSERT INTO student VALUES(194003,'ROCKY','2000-03-10','ECE','PUNJAB');
INSERT INTO student VALUES(194004,'TRIBHUVAN','1999-03-15','CSE','ANDHRA PRADESH');
INSERT INTO student VALUES(194005,'VAMSI','2000-04-19','CSE','TELANGANA');

SELECT * FROM student;
SELECT * FROM student WHERE branch='CSE'AND state='PUNJAB';
SELECT * FROM student WHERE branch='CSE' OR branch='ECE';
SELECT * FROM student WHERE NOT state='PUNJAB';
SELECT * FROM student WHERE Name NOT LIKE 'VAMSI';
SELECT * FROM student WHERE student_name NOT LIKE 'VAMSI' ;
SELECT * FROM student WHERE student_name IN ('PRAKASH', 'ROCKY', 'TRIBHUVAN');
SELECT * FROM student WHERE student_name BETWEEN 194002 AND 194005;

